FROM nginx
# ДОКЕР-ФАЙЛ для работы с бэком который не в контейнере

# docker build -t only_front:latest --file Dockerfile_without_back .

# 

# вся статика, которую nginx будет раздавать
COPY . /usr/share/nginx/html/
# конфиг файл
COPY ./nginx_without_back.conf /etc/nginx/nginx.conf

EXPOSE 8000
